// TYPES INPUT TRANSFER CHECKBOX
export const CHECKED_ALL = 'TRANSFER/CHECKED_ALL'
export const CHECKED_NOT = 'TRANSFER/CHECKED_NOT'
export const CHECKED_ONE = 'TRANSFER/CHECKED_ONE'
export const CHECKED_TWO = 'TRANSFER/CHECKED_TWO'
export const CHECKED_THREE = 'TRANSFER/CHECKED_THREE'
